/**
 * UI fixtures only. These exist so the interface can be reviewed before the
 * FastAPI backend exists. No business rules live here — prices, match scores
 * and maintenance states are treated as values the API will supply.
 */
import novaXe from "@/assets/vehicle-nova-xe.jpg";
import titanGt from "@/assets/vehicle-titan-gt.jpg";
import swiftNano from "@/assets/vehicle-swift-nano.jpg";
import obsidian from "@/assets/vehicle-obsidian.jpg";
import cargoMax from "@/assets/vehicle-cargo-max.jpg";
import harbor from "@/assets/vehicle-harbor.jpg";

import type {
  AdminOverview,
  Booking,
  MaintenanceRecord,
  Payment,
  PlatformUser,
  Review,
  Vehicle,
  Vendor,
  VendorOverview,
} from "@/types";

export const vehicleImages = [novaXe, titanGt, swiftNano, obsidian, cargoMax, harbor];

const vendors: Vendor[] = [
  {
    id: "vd_01",
    name: "Northline Mobility",
    rating: 4.9,
    tripsCompleted: 1284,
    memberSince: "2021",
    responseTimeMinutes: 8,
    verified: true,
    city: "Berlin",
    vehicleCount: 24,
    status: "active",
  },
  {
    id: "vd_02",
    name: "Kestrel Fleet Co.",
    rating: 4.7,
    tripsCompleted: 642,
    memberSince: "2022",
    responseTimeMinutes: 15,
    verified: true,
    city: "Hamburg",
    vehicleCount: 12,
    status: "active",
  },
  {
    id: "vd_03",
    name: "Meridian Auto Rentals",
    rating: 4.5,
    tripsCompleted: 318,
    memberSince: "2023",
    responseTimeMinutes: 24,
    verified: false,
    city: "Munich",
    vehicleCount: 7,
    status: "pending",
  },
];

export const mockVendors = vendors;

const baseReviews: Review[] = [
  {
    id: "rv_1",
    author: "Marion K.",
    rating: 5,
    date: "2026-06-18",
    comment:
      "Immaculate car, handover took four minutes. Charging card was in the glovebox exactly as described.",
  },
  {
    id: "rv_2",
    author: "Devon A.",
    rating: 4,
    date: "2026-05-30",
    comment:
      "Great range and very comfortable on the motorway. Pickup garage was a little hard to find.",
  },
  {
    id: "rv_3",
    author: "Priya S.",
    rating: 5,
    date: "2026-05-02",
    comment: "Third rental with this vendor. Consistently spotless and always on time.",
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: "veh_nova_xe",
    name: "Nova XE Model S",
    type: "Sedan",
    pricePerDay: 142,
    currency: "USD",
    rating: 4.92,
    reviewCount: 128,
    location: "Berlin, DE",
    availability: "available",
    maintenanceStatus: "good",
    imageUrl: novaXe,
    gallery: [novaXe, obsidian, harbor],
    description:
      "A long-range electric sedan built for quiet intercity work. Adaptive suspension, heated seats and a 480 km real-world range make it the default choice for multi-day business trips.",
    features: [
      "Adaptive cruise control",
      "480 km range",
      "Fast charge 20-80% in 22 min",
      "Heated seats",
      "CarPlay & Android Auto",
      "360° parking cameras",
    ],
    specs: {
      seats: 5,
      doors: 4,
      fuel: "Electric",
      transmission: "Automatic",
      rangeKm: 480,
      luggage: 3,
      year: 2025,
    },
    vendor: vendors[0]!,
    matchScore: 98,
  },
  {
    id: "veh_titan_gt",
    name: "Titan GT Utility",
    type: "SUV",
    pricePerDay: 189,
    currency: "USD",
    rating: 4.88,
    reviewCount: 45,
    location: "Berlin, DE",
    availability: "booked",
    maintenanceStatus: "service_due_soon",
    imageUrl: titanGt,
    gallery: [titanGt, harbor, novaXe],
    description:
      "All-wheel-drive hybrid SUV with a roof rack and towing package. Built for crew transport, gear hauling and rough approach roads.",
    features: [
      "All-wheel drive",
      "Roof rack included",
      "Towing package",
      "Heated windscreen",
      "Off-road drive modes",
      "Third-row seating",
    ],
    specs: {
      seats: 7,
      doors: 5,
      fuel: "Hybrid",
      transmission: "Automatic",
      rangeKm: 720,
      luggage: 5,
      year: 2024,
    },
    vendor: vendors[1]!,
    matchScore: 92,
  },
  {
    id: "veh_swift_nano",
    name: "Swift E-Nano",
    type: "Hatchback",
    pricePerDay: 85,
    currency: "USD",
    rating: 4.96,
    reviewCount: 230,
    location: "Berlin, DE",
    availability: "available",
    maintenanceStatus: "good",
    imageUrl: swiftNano,
    gallery: [swiftNano, novaXe, obsidian],
    description:
      "Compact two-seat city EV. Fits any parking gap, charges from a standard wall socket and costs almost nothing to run inside the low-emission zone.",
    features: [
      "City parking assist",
      "230 km range",
      "Wall-socket charging",
      "Low-emission zone permit",
      "Bluetooth audio",
      "Reversing camera",
    ],
    specs: {
      seats: 2,
      doors: 3,
      fuel: "Electric",
      transmission: "Automatic",
      rangeKm: 230,
      luggage: 1,
      year: 2025,
    },
    vendor: vendors[0]!,
    matchScore: 85,
  },
  {
    id: "veh_obsidian",
    name: "Obsidian Executive L",
    type: "Luxury",
    pricePerDay: 264,
    currency: "USD",
    rating: 4.81,
    reviewCount: 62,
    location: "Munich, DE",
    availability: "available",
    maintenanceStatus: "good",
    imageUrl: obsidian,
    gallery: [obsidian, novaXe, titanGt],
    description:
      "Chauffeur-grade executive saloon with rear climate control, acoustic glazing and an airport meet-and-greet option at pickup.",
    features: [
      "Rear climate control",
      "Acoustic glazing",
      "Massage seats",
      "Airport meet & greet",
      "Premium audio",
      "Ambient lighting",
    ],
    specs: {
      seats: 5,
      doors: 4,
      fuel: "Petrol",
      transmission: "Automatic",
      rangeKm: 850,
      luggage: 4,
      year: 2025,
    },
    vendor: vendors[2]!,
    matchScore: 74,
  },
  {
    id: "veh_cargo_max",
    name: "Cargo Max T-Series",
    type: "Van",
    pricePerDay: 118,
    currency: "USD",
    rating: 4.62,
    reviewCount: 91,
    location: "Hamburg, DE",
    availability: "maintenance",
    maintenanceStatus: "under_maintenance",
    imageUrl: cargoMax,
    gallery: [cargoMax, titanGt, harbor],
    description:
      "High-roof cargo van with 11 m³ of load space, a low loading sill and lashing rails. Registered for city delivery access.",
    features: [
      "11 m³ load space",
      "Low loading sill",
      "Lashing rails",
      "Reversing camera",
      "Delivery zone permit",
      "Bulkhead partition",
    ],
    specs: {
      seats: 3,
      doors: 4,
      fuel: "Diesel",
      transmission: "Manual",
      rangeKm: 900,
      luggage: 9,
      year: 2023,
    },
    vendor: vendors[1]!,
    matchScore: 61,
  },
  {
    id: "veh_harbor",
    name: "Harbor Crossover H4",
    type: "SUV",
    pricePerDay: 132,
    currency: "USD",
    rating: 4.74,
    reviewCount: 154,
    location: "Hamburg, DE",
    availability: "available",
    maintenanceStatus: "good",
    imageUrl: harbor,
    gallery: [harbor, titanGt, swiftNano],
    description:
      "Hybrid family crossover with a large boot, child-seat anchors and a panoramic roof. Comfortable on long coastal drives.",
    features: [
      "Panoramic roof",
      "ISOFIX anchors",
      "Lane keep assist",
      "Wireless charging",
      "Boot rails",
      "Hybrid drivetrain",
    ],
    specs: {
      seats: 5,
      doors: 5,
      fuel: "Hybrid",
      transmission: "Automatic",
      rangeKm: 780,
      luggage: 4,
      year: 2024,
    },
    vendor: vendors[2]!,
    matchScore: 88,
  },
];

export const mockReviews: Record<string, Review[]> = Object.fromEntries(
  mockVehicles.map((v) => [
    v.id,
    baseReviews.map((r) => ({ ...r, id: `${v.id}_${r.id}`, vehicleName: v.name })),
  ]),
);

export const mockBookings: Booking[] = [
  {
    id: "bk_1",
    reference: "VN-902341",
    vehicleId: "veh_nova_xe",
    vehicleName: "Nova XE Model S",
    vehicleImage: novaXe,
    customerName: "Alex Rivera",
    vendorName: "Northline Mobility",
    pickupLocation: "Berlin Hauptbahnhof",
    startDate: "2026-08-09T09:00:00Z",
    endDate: "2026-08-13T18:00:00Z",
    status: "active",
    paymentStatus: "paid",
    total: 682,
    currency: "USD",
  },
  {
    id: "bk_2",
    reference: "VN-902342",
    vehicleId: "veh_harbor",
    vehicleName: "Harbor Crossover H4",
    vehicleImage: harbor,
    customerName: "Alex Rivera",
    vendorName: "Meridian Auto Rentals",
    pickupLocation: "Hamburg Airport",
    startDate: "2026-08-24T10:00:00Z",
    endDate: "2026-08-28T10:00:00Z",
    status: "upcoming",
    paymentStatus: "paid",
    total: 548,
    currency: "USD",
  },
  {
    id: "bk_3",
    reference: "VN-902343",
    vehicleId: "veh_swift_nano",
    vehicleName: "Swift E-Nano",
    vehicleImage: swiftNano,
    customerName: "Alex Rivera",
    vendorName: "Northline Mobility",
    pickupLocation: "Berlin Mitte",
    startDate: "2026-09-02T08:00:00Z",
    endDate: "2026-09-04T20:00:00Z",
    status: "upcoming",
    paymentStatus: "pending",
    total: 178,
    currency: "USD",
  },
  {
    id: "bk_4",
    reference: "VN-901980",
    vehicleId: "veh_obsidian",
    vehicleName: "Obsidian Executive L",
    vehicleImage: obsidian,
    customerName: "Alex Rivera",
    vendorName: "Meridian Auto Rentals",
    pickupLocation: "Munich Airport T2",
    startDate: "2026-06-11T07:00:00Z",
    endDate: "2026-06-14T19:00:00Z",
    status: "completed",
    paymentStatus: "paid",
    total: 812,
    currency: "USD",
  },
  {
    id: "bk_5",
    reference: "VN-901742",
    vehicleId: "veh_titan_gt",
    vehicleName: "Titan GT Utility",
    vehicleImage: titanGt,
    customerName: "Alex Rivera",
    vendorName: "Kestrel Fleet Co.",
    pickupLocation: "Berlin Tempelhof",
    startDate: "2026-04-02T09:00:00Z",
    endDate: "2026-04-05T09:00:00Z",
    status: "cancelled",
    paymentStatus: "refunded",
    total: 567,
    currency: "USD",
  },
];

export const mockPayments: Payment[] = [
  {
    id: "pm_1",
    bookingRef: "VN-902341",
    method: "Visa •••• 4417",
    amount: 682,
    currency: "USD",
    status: "paid",
    date: "2026-08-07",
    payer: "Alex Rivera",
  },
  {
    id: "pm_2",
    bookingRef: "VN-902342",
    method: "Apple Pay",
    amount: 548,
    currency: "USD",
    status: "paid",
    date: "2026-08-01",
    payer: "Alex Rivera",
  },
  {
    id: "pm_3",
    bookingRef: "VN-902343",
    method: "Visa •••• 4417",
    amount: 178,
    currency: "USD",
    status: "pending",
    date: "2026-08-10",
    payer: "Alex Rivera",
  },
  {
    id: "pm_4",
    bookingRef: "VN-901742",
    method: "Visa •••• 4417",
    amount: 567,
    currency: "USD",
    status: "refunded",
    date: "2026-04-03",
    payer: "Alex Rivera",
  },
];

export const mockMaintenance: MaintenanceRecord[] = [
  {
    id: "mt_1",
    vehicleId: "veh_titan_gt",
    vehicleName: "Titan GT Utility",
    maintenanceType: "Brake pad replacement",
    description: "Brake pads need replacement",
    maintenanceDate: "2026-08-19",
    cost: 2500,
    status: "scheduled",
  },
  {
    id: "mt_2",
    vehicleId: "veh_cargo_max",
    vehicleName: "Cargo Max T-Series",
    maintenanceType: "Clutch assembly overhaul",
    description: "Clutch assembly requires servicing",
    maintenanceDate: "2026-08-12",
    cost: 5000,
    status: "in_progress",
  },
  {
    id: "mt_3",
    vehicleId: "veh_nova_xe",
    vehicleName: "Nova XE Model S",
    maintenanceType: "Annual inspection",
    description: "Annual vehicle inspection",
    maintenanceDate: "2026-11-04",
    cost: 1500,
    status: "completed",
  },
  {
    id: "mt_4",
    vehicleId: "veh_harbor",
    vehicleName: "Harbor Crossover H4",
    maintenanceType: "Tyre rotation",
    description: "Routine tyre rotation",
    maintenanceDate: "2026-10-21",
    cost: 1000,
    status: "scheduled",
  },
];

export const mockUsers: PlatformUser[] = [
  {
    id: "us_1",
    name: "Alex Rivera",
    email: "alex.rivera@example.com",
    role: "customer",
    status: "active",
    joinedAt: "2024-02-11",
    bookings: 14,
  },
  {
    id: "us_2",
    name: "Marion Klein",
    email: "m.klein@example.com",
    role: "customer",
    status: "active",
    joinedAt: "2025-01-08",
    bookings: 6,
  },
  {
    id: "us_3",
    name: "Northline Mobility",
    email: "ops@northline.example",
    role: "vendor",
    status: "active",
    joinedAt: "2021-06-02",
    bookings: 1284,
  },
  {
    id: "us_4",
    name: "Meridian Auto Rentals",
    email: "hello@meridian.example",
    role: "vendor",
    status: "pending",
    joinedAt: "2026-07-28",
    bookings: 0,
  },
  {
    id: "us_5",
    name: "Devon Ashby",
    email: "devon.a@example.com",
    role: "customer",
    status: "suspended",
    joinedAt: "2025-09-19",
    bookings: 2,
  },
  {
    id: "us_6",
    name: "Sam Okafor",
    email: "sam.okafor@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2023-03-14",
    bookings: 0,
  },
];

const months = ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"];

export const mockVendorOverview: VendorOverview = {
  totalVehicles: 24,
  activeBookings: 9,
  upcomingBookings: 14,
  revenue: 42900,
  currency: "USD",
  revenueSeries: months.map((label, i) => ({
    label,
    value: [4200, 5100, 4780, 6120, 6890, 7420, 8390][i] ?? 0,
  })),
  utilisationSeries: months.map((label, i) => ({
    label,
    value: [62, 68, 66, 74, 81, 88, 94][i] ?? 0,
  })),
};

export const mockAdminOverview: AdminOverview = {
  totalUsers: 12840,
  totalVendors: 268,
  totalVehicles: 3419,
  activeRentals: 486,
  totalBookings: 28714,
  revenue: 1284900,
  currency: "USD",
  revenueSeries: months.map((label, i) => ({
    label,
    value: [128000, 141000, 137500, 168200, 181400, 204800, 236900][i] ?? 0,
    secondary: [98000, 106000, 101000, 122000, 133000, 148000, 171000][i] ?? 0,
  })),
  bookingsByCategory: [
    { label: "Sedan", value: 8420 },
    { label: "SUV", value: 7310 },
    { label: "Hatchback", value: 5120 },
    { label: "Van", value: 3980 },
    { label: "Luxury", value: 2410 },
    { label: "Bike", value: 1474 },
  ],
};

export const mockTestimonials = [
  {
    id: "ts_1",
    name: "Marion Klein",
    role: "Operations lead, Frachtwerk",
    quote:
      "We moved our whole regional fleet onto Ridefleet. Handover paperwork went from twenty minutes to a QR code.",
    rating: 5,
  },
  {
    id: "ts_2",
    name: "Devon Ashby",
    role: "Independent contractor",
    quote:
      "The maintenance alerts alone paid for themselves. I have not had an unplanned workshop day in seven months.",
    rating: 5,
  },
  {
    id: "ts_3",
    name: "Priya Sharma",
    role: "Frequent traveller",
    quote:
      "Booking takes under a minute and the recommended list is genuinely accurate. It always finds me an EV near the station.",
    rating: 4,
  },
];
