/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as BookingVehicleIdRouteImport } from './routes/booking.$vehicleId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles.$vehicleId'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorBookingsRouteImport } from './routes/vendor.bookings'
import { Route as VendorEarningsRouteImport } from './routes/vendor.earnings'
import { Route as VendorMaintenanceRouteImport } from './routes/vendor.maintenance'
import { Route as VendorVehiclesRouteImport } from './routes/vendor.vehicles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/admin/maintenance',
  path: '/admin/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/admin/vehicles',
  path: '/admin/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingVehicleIdRoute = BookingVehicleIdRouteImport.update({
  id: '/booking/$vehicleId',
  path: '/booking/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/dashboard/favorites',
  path: '/dashboard/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/dashboard/payments',
  path: '/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorBookingsRoute = VendorBookingsRouteImport.update({
  id: '/vendor/bookings',
  path: '/vendor/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorEarningsRoute = VendorEarningsRouteImport.update({
  id: '/vendor/earnings',
  path: '/vendor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorMaintenanceRoute = VendorMaintenanceRouteImport.update({
  id: '/vendor/maintenance',
  path: '/vendor/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVehiclesRoute = VendorVehiclesRouteImport.update({
  id: '/vendor/vehicles',
  path: '/vendor/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/booking/$vehicleId': typeof BookingVehicleIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vendor/bookings': typeof VendorBookingsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/maintenance': typeof VendorMaintenanceRoute
  '/vendor/vehicles': typeof VendorVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/booking/$vehicleId': typeof BookingVehicleIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vendor/bookings': typeof VendorBookingsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/maintenance': typeof VendorMaintenanceRoute
  '/vendor/vehicles': typeof VendorVehiclesRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/vendor': typeof VendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/booking/$vehicleId': typeof BookingVehicleIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/vendor/bookings': typeof VendorBookingsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/maintenance': typeof VendorMaintenanceRoute
  '/vendor/vehicles': typeof VendorVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/bookings'
    | '/admin/maintenance'
    | '/admin/payments'
    | '/admin/users'
    | '/admin/vehicles'
    | '/admin/vendors'
    | '/booking/$vehicleId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/vehicles/$vehicleId'
    | '/vendor/bookings'
    | '/vendor/earnings'
    | '/vendor/maintenance'
    | '/vendor/vehicles'
    | '/admin/'
    | '/dashboard/'
    | '/vehicles/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/bookings'
    | '/admin/maintenance'
    | '/admin/payments'
    | '/admin/users'
    | '/admin/vehicles'
    | '/admin/vendors'
    | '/booking/$vehicleId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/vehicles/$vehicleId'
    | '/vendor/bookings'
    | '/vendor/earnings'
    | '/vendor/maintenance'
    | '/vendor/vehicles'
    | '/admin'
    | '/dashboard'
    | '/vehicles'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/bookings'
    | '/admin/maintenance'
    | '/admin/payments'
    | '/admin/users'
    | '/admin/vehicles'
    | '/admin/vendors'
    | '/booking/$vehicleId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/vehicles/$vehicleId'
    | '/vendor/bookings'
    | '/vendor/earnings'
    | '/vendor/maintenance'
    | '/vendor/vehicles'
    | '/admin/'
    | '/dashboard/'
    | '/vehicles/'
    | '/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  BookingVehicleIdRoute: typeof BookingVehicleIdRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRoute
  VendorBookingsRoute: typeof VendorBookingsRoute
  VendorEarningsRoute: typeof VendorEarningsRoute
  VendorMaintenanceRoute: typeof VendorMaintenanceRoute
  VendorVehiclesRoute: typeof VendorVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$vehicleId': {
      id: '/booking/$vehicleId'
      path: '/booking/$vehicleId'
      fullPath: '/booking/$vehicleId'
      preLoaderRoute: typeof BookingVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/bookings': {
      id: '/vendor/bookings'
      path: '/vendor/bookings'
      fullPath: '/vendor/bookings'
      preLoaderRoute: typeof VendorBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/earnings': {
      id: '/vendor/earnings'
      path: '/vendor/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof VendorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/maintenance': {
      id: '/vendor/maintenance'
      path: '/vendor/maintenance'
      fullPath: '/vendor/maintenance'
      preLoaderRoute: typeof VendorMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/vehicles': {
      id: '/vendor/vehicles'
      path: '/vendor/vehicles'
      fullPath: '/vendor/vehicles'
      preLoaderRoute: typeof VendorVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  BookingVehicleIdRoute: BookingVehicleIdRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  VehiclesVehicleIdRoute: VehiclesVehicleIdRoute,
  VendorBookingsRoute: VendorBookingsRoute,
  VendorEarningsRoute: VendorEarningsRoute,
  VendorMaintenanceRoute: VendorMaintenanceRoute,
  VendorVehiclesRoute: VendorVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  VendorIndexRoute: VendorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
